# File derived from https://github.com/CTFd/CTFd/blob/3.5.0/docker-compose.yml
# Copyright 2015-present CTFd LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
# https://github.com/CTFd/CTFd/blob/3.5.0/LICENSE

version: '2'

services:
  ctfd:
    image: ctfd/ctfd:3.5.1
    restart: always
    ports:
      - "8000:8000"
    environment:
      - UPLOAD_FOLDER=/var/uploads
      - DATABASE_URL=mysql+pymysql://${MYSQL_USER}:${MYSQL_PASSWORD}@db/${MYSQL_DATABASE}
      - REDIS_URL=redis://cache:6379
      - WORKERS=1
      - LOG_FOLDER=/var/log/CTFd
      - ACCESS_LOG=-
      - ERROR_LOG=-
      - REVERSE_PROXY=true
    volumes:
      - .data/CTFd/logs:/var/log/CTFd
      - .data/CTFd/uploads:/var/uploads
    depends_on:
      - db
    networks:
      default:
      internal:


  nginx:
    image: nginx:stable
    restart: always
    volumes:
      - ./nginx/http.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    depends_on:
      - ctfd

  db:
    image: mariadb:10.4
    restart: always
    env_file: .env
    volumes:
      - .data/mysql:/var/lib/mysql
    networks:
      internal: # This command is required to set important mariadb defaults
    command:
      [
        mysqld,
        --character-set-server=utf8mb4,
        --collation-server=utf8mb4_unicode_ci,
        --wait_timeout=28800,
        --log-warnings=0
      ]

  cache:
    image: redis:4
    restart: always
    volumes:
      - .data/redis:/data
    networks:
      internal:


networks:
  default:
  internal:
    internal: true
